services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    configs:
      - source: my_config_2
        target: /etc/nginx/conf.d/default.conf
    command: ["/usr/sbin/nginx-debug", "-g", "daemon off;"]

  worker:
    image: uffizzicloud/example-worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizzicloud/example-vote:latest

  result:
    image: uffizzicloud/example-result:latest

x-uffizzi-ingress:
  service: nginx
  port: 8080
  
x-uffizzi-continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
  
configs:
  my_config_2:
    file: ./config2/vote2.conf
