services:
  redis:
    image: redis:latest

  hello-world:
    image: nginx
    healthcheck:
      disable: true

x-uffizzi:
  continuous_preview:
    delete_preview_after: 1h

x-uffizzi-ingress:
  service: hello-world
  port: 80
