version: '3'

services:
  app:
    image: ttl.sh/test-node-zipofar:9h
    entrypoint: /bin/bash
    command:
      - "-c"
      - "tail /dev/zero"

x-uffizzi:
  ingress:
    service: app
    port: 8080

  continuous_preview:
    delete_preview_after: 10h
