services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    env_file: ${VOTE_APP_POSTGRES_ENVS}

  nginx:
    image: nginx:latest
    configs:
      - source: vote.conf
        target: /etc/nginx/conf.d

  worker:
    image: gcr.io/uffizzi-pro-qa-gke/example-worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: gcr.io/uffizzi-pro-qa-gke/example-vote:latest

  result:
    image: gcr.io/uffizzi-pro-qa-gke/example-result:latest

ingress:
  service: nginx
  port: 8080

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 10h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
