services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST: test

  nginx:
    image: nginx:latest
    configs:
      - source: /configs/vote.conf
        target: /etc/nginx/conf.d

  worker:
    build:
      context: https://github.com/NealArw/example-voting-worker:main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build:
      context: https://github.com/NealArw/example-voting-vote:main
      dockerfile: Dockerfile

  result:
    build:
      context: https://github.com/NealArw/example-voting-result:main
      dockerfile: Dockerfile

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: false

ingress:
  service: nginx
  port: 8080
