services:
  hello-world:
    build:
      context: https://github.com/NealArw/hello-world-1#compose-test
      dockerfile: Dockerfile.args
      args:
        - IMAGES_PATH=images
        - TEST_ARG=Hello from compose

x-uffizzi-ingress:
  service: hello-world
  port: 80
