services:
  webhook:
    image: uffizzitest/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST: test1
    deploy:
      x-uffizzi-auto-deploy-updates: false

ingress:
  service: webhook
  port: 80

continuous_preview:
  tag_pattern: uffizzi_request_*
  deploy_preview_when_pull_request_is_opened: false
  delete_preview_when_pull_request_is_closed: false
  delete_preview_after: 120h
  share_to_github: false
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
