services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    configs:
      - source: my_config_2
        target: /etc/nginx/conf.d/default.conf

  worker:
    image: gcr.io/uffizzi-pro-qa-gke/example-worker
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: gcr.io/uffizzi-pro-qa-gke/example-vote:latest

  result:
    image: gcr.io/uffizzi-pro-qa-gke/example-result:latest

configs:
  my_config_2:
    file: ./config2/vote2.conf

x-uffizzi-ingress:
  service: nginx
  port: 8080

x-uffizzi-continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  delete_preview_after: 20h
  share_to_github: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_image_tag_is_updated: true
