services:
  hello-world:
    build:
      context: https://github.com/NealArw/hello-world-1:master

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true

ingress:
  service: hello-world
  port: 80
