services:
  webhook:
    image: gcr.io/uffizzi-pro-qa-gke/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST: test12
    deploy:
      x-uffizzi-auto-deploy-updates: true
      resources:
        limits:
          memory: 125M

x-uffizzi-ingress:
  service: webhook
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 1h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
