services:
  webhook:
    image: 263049488290.dkr.ecr.us-east-1.amazonaws.com/webhooks-test-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

x-uffizzi-ingress:
  service: webhook
  port: 80

x-uffizzi-continuous-preview:
  delete_preview_after: 2h
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
