services:
  hello-world:
    build:
      context: https://github.com/7R41N33/hello-world:master
    configs:
      - source: vote.conf
        target: /etc/nginx

ingress:
  service: hello-world
  port: 80
